apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
data:
  MP3_QUEUE: "mp3"
  VIDEO_QUEUE: "video"
  MONGODB_URI: "mongodb://nasi:nasi1234@mongodb:27017/?authSource=admin&readPreference=secondary&directConnection=true&ssl=false"
